runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /android/upload_image
  script: android_handler.app

- url: /android/upload_image_url
  script: android_handler.app

- url: /android/view_all_streams
  script: android_handler.app

- url: /android/view_all_images
  script: android_handler.app

- url: /android/view_nearby_images
  script: android_handler.app

- url: /
  script: connexus.app

- url: /manage
  script: connexus.app
  login: required

- url: /create
  script: connexus.app
  login: required

- url: /view
  script: connexus.app

- url: /view_one
  script: connexus.app

- url: /geo_view
  script: connexus.app

- url: /search
  script: connexus.app

- url: /trending
  script: connexus.app

- url: /social
  script: connexus.app
  login: required

- url: /error
  script: connexus.app
  login: required

- url: /updatetrending
  script: connexus.app

- url: /digest5min
  script: connexus.app

- url: /digest1hr
  script: connexus.app

- url: /digest24hr
  script: connexus.app

- url: /upload_image
  script: connexus.app

- url: /view_image
  script: connexus.app

- url: .*
  script: connexus.app

# Path variables
- url: /resources
  static_dir: resources

# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]



